#!/bin/bash

# Цвет фона
REDB="$(printf '\033[48;5;124m')"
GREENB="$(printf '\033[48;5;118m')"
YELLOWB="$(printf '\033[48;5;226m')"
SIRENB="$(printf '\033[48;5;135m')"
PURPLEB="$(printf '\033[48;5;')"
CYANB="$(printf '\033[48;5;')"
WHITEB="$(printf '\033[48;5;')"

# Цвет текста
RED="$(printf '\033[38;5;196m')"
GREEN="$(printf '\033[0;32m')"
YELLOW="$(printf '\033[0;33m')"
SIREN="$(printf '\033[0;34m')"
PURPLE="$(printf '\033[38;5;128m')"
CYAN="$(printf '\033[0;36m')"
WHITE="$(printf '\033[0;37m')"
BLACK="$(printf '\033[38;5;232m')"
RESET="$(printf '\033[0m')"
TIRE="$(printf '\033[4m')"
